language: node_js

node_js:
  - "20"

install:
  - npm install

script:
  - npm run build

addons:
  sonarcloud:
    organization: "your-org"
    token:
      secure: "YOUR_TOKEN"

after_success:
  - sonar-scanner